package HostInfo.hostinfo;


/**
* hostinfo/hostInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hostinfo.idl
* Thursday, June 18, 2020 8:11:40 AM CEST
*/

public interface hostInfo extends hostInfoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface hostInfo
