package HostInfo.hostinfo;


/**
* hostinfo/hostInfoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hostinfo.idl
* Thursday, June 18, 2020 8:11:40 AM CEST
*/

public interface hostInfoOperations 
{
  String getDayTime ();
  String getAddress ();
} // interface hostInfoOperations
