package POADirectory.dirinfo;

/**
* dirinfo/Directory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dirinfo.idl
* Thursday, June 18, 2020 6:18:13 PM CEST
*/

public interface Directory extends DirectoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Directory
