package POAServantLocator.test;


/**
* test/TesterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* Thursday, June 18, 2020 6:34:05 PM CEST
*/

public interface TesterOperations 
{
  String getMessage ();
} // interface TesterOperations
