package POAgetfile.dirinfo;

/**
* dirinfo/DirectoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dirinfo.idl
* Thursday, June 18, 2020 6:33:30 PM CEST
*/

public final class DirectoryHolder implements org.omg.CORBA.portable.Streamable
{
  public POAgetfile.dirinfo.Directory value = null;

  public DirectoryHolder ()
  {
  }

  public DirectoryHolder (POAgetfile.dirinfo.Directory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POAgetfile.dirinfo.DirectoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POAgetfile.dirinfo.DirectoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POAgetfile.dirinfo.DirectoryHelper.type ();
  }

}
