package POADirectory.dirinfo.DirectoryPackage;

/**
* dirinfo/DirectoryPackage/dlistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dirinfo.idl
* Thursday, June 18, 2020 6:18:13 PM CEST
*/

public final class dlistHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public dlistHolder ()
  {
  }

  public dlistHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POADirectory.dirinfo.DirectoryPackage.dlistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POADirectory.dirinfo.DirectoryPackage.dlistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POADirectory.dirinfo.DirectoryPackage.dlistHelper.type ();
  }

}
