package POASaveObject.dbtest;


/**
* dbtest/dbFaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbtest.idl
* Thursday, June 18, 2020 6:33:42 PM CEST
*/

abstract public class dbFaceHelper
{
  private static String  _id = "IDL:dbtest/dbFace:1.0";

  public static void insert (org.omg.CORBA.Any a, POASaveObject.dbtest.dbFace that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static POASaveObject.dbtest.dbFace extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (POASaveObject.dbtest.dbFaceHelper.id (), "dbFace");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static POASaveObject.dbtest.dbFace read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_dbFaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, POASaveObject.dbtest.dbFace value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static POASaveObject.dbtest.dbFace narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof POASaveObject.dbtest.dbFace)
      return (POASaveObject.dbtest.dbFace)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      POASaveObject.dbtest._dbFaceStub stub = new POASaveObject.dbtest._dbFaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static POASaveObject.dbtest.dbFace unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof POASaveObject.dbtest.dbFace)
      return (POASaveObject.dbtest.dbFace)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      POASaveObject.dbtest._dbFaceStub stub = new POASaveObject.dbtest._dbFaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
