package POASaveObject.dbtest;


/**
* dbtest/dbFaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbtest.idl
* Thursday, June 18, 2020 6:33:42 PM CEST
*/

public interface dbFaceOperations 
{
  String getName (int primary_key);
  String getLastQuery ();
} // interface dbFaceOperations
