package POASaveObject.dbtest;


/**
* dbtest/dbFace.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbtest.idl
* Thursday, June 18, 2020 6:33:42 PM CEST
*/

public interface dbFace extends dbFaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface dbFace
