package POASaveObject.dbtest;

/**
* dbtest/dbFaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbtest.idl
* Thursday, June 18, 2020 6:33:42 PM CEST
*/

public final class dbFaceHolder implements org.omg.CORBA.portable.Streamable
{
  public POASaveObject.dbtest.dbFace value = null;

  public dbFaceHolder ()
  {
  }

  public dbFaceHolder (POASaveObject.dbtest.dbFace initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POASaveObject.dbtest.dbFaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POASaveObject.dbtest.dbFaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POASaveObject.dbtest.dbFaceHelper.type ();
  }

}
