package CarPrice.examples.carinfo;


/**
* examples/carinfo/_carPriceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from carinfo.idl
* sobota, 5 listopad 2005 14:36:30 CET
*/

public abstract class _carPriceImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements CarPrice.examples.carinfo.carPrice, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _carPriceImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCarPrice", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // examples/carinfo/carPrice/getCarPrice
       {
         String model = in.read_string ();
         float $result = (float)0;
         $result = this.getCarPrice (model);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:examples/carinfo/carPrice:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _carPriceImplBase
