package CarPrice.examples.carinfo;

/**
* examples/carinfo/carPriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from carinfo.idl
* sobota, 5 listopad 2005 14:36:30 CET
*/

public final class carPriceHolder implements org.omg.CORBA.portable.Streamable
{
  public CarPrice.examples.carinfo.carPrice value = null;

  public carPriceHolder ()
  {
  }

  public carPriceHolder (CarPrice.examples.carinfo.carPrice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CarPrice.examples.carinfo.carPriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CarPrice.examples.carinfo.carPriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CarPrice.examples.carinfo.carPriceHelper.type ();
  }

}
