package CarPrice.examples.carinfo;


/**
* examples/carinfo/carPriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from carinfo.idl
* sobota, 5 listopad 2005 14:36:30 CET
*/

public interface carPriceOperations 
{
  float getCarPrice (String model);
} // interface carPriceOperations
