package POAVector.vtools;

/**
* vtools/CounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/


// licznik
public final class CounterHolder implements org.omg.CORBA.portable.Streamable
{
  public POAVector.vtools.Counter value = null;

  public CounterHolder ()
  {
  }

  public CounterHolder (POAVector.vtools.Counter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POAVector.vtools.CounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POAVector.vtools.CounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POAVector.vtools.CounterHelper.type ();
  }

}
