package POAVector.vtools;


/**
* vtools/CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/


// licznik
public interface CounterOperations 
{
  int count ();
  void count (int newCount);
  void inc ();
  void dec ();
} // interface CounterOperations
