package POAVector.vtools;


/**
* vtools/Vector.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/


// wector
public interface Vector extends VectorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final short MAXSIZE = (short)(10);
} // interface Vector
