package POAVector.vtools;


/**
* vtools/VectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/


// wector
public interface VectorOperations 
{

  // dodawanie wektorow c = a + b
  int[] add (short size, int[] a, int[] b);

  // odejmowanie wektorow c = a - b
  int[] sub (short size, int[] a, int[] b);
} // interface VectorOperations
