package POAVector.vtools;

/**
* vtools/VectorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/


// wector
public final class VectorHolder implements org.omg.CORBA.portable.Streamable
{
  public POAVector.vtools.Vector value = null;

  public VectorHolder ()
  {
  }

  public VectorHolder (POAVector.vtools.Vector initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POAVector.vtools.VectorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POAVector.vtools.VectorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POAVector.vtools.VectorHelper.type ();
  }

}
