package POAVector.vtools.VectorPackage;


/**
* vtools/VectorPackage/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vector.idl
* Thursday, June 18, 2020 6:34:21 PM CEST
*/

public final class arrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public arrayHolder ()
  {
  }

  public arrayHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = POAVector.vtools.VectorPackage.arrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    POAVector.vtools.VectorPackage.arrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return POAVector.vtools.VectorPackage.arrayHelper.type ();
  }

}
