package POAServantActivator.test;


/**
* test/Tester.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* Thursday, June 18, 2020 6:33:54 PM CEST
*/

public interface Tester extends TesterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tester
