package HostInfoFile.hostinfo;

/**
* hostinfo/hostInfoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hostinfo.idl
* Thursday, June 18, 2020 4:58:27 PM CEST
*/

public interface hostInfoOperations 
{
  String getDayTime ();
  String getAddress ();
} // interface hostInfoOperations
