package HostInfoFile.hostinfo;

/**
* hostinfo/hostInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hostinfo.idl
* Thursday, June 18, 2020 4:58:27 PM CEST
*/

public final class hostInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public HostInfoFile.hostinfo.hostInfo value = null;

  public hostInfoHolder ()
  {
  }

  public hostInfoHolder (HostInfoFile.hostinfo.hostInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HostInfoFile.hostinfo.hostInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HostInfoFile.hostinfo.hostInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HostInfoFile.hostinfo.hostInfoHelper.type ();
  }

}
