package Callback.CallbackApp;


/**
* CallbackApp/_MsgCallbackImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CallbackExample.idl
* sobota, 5 listopad 2005 14:50:17 CET
*/

public abstract class _MsgCallbackImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Callback.CallbackApp.MsgCallback, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MsgCallbackImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callback", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CallbackApp/MsgCallback/callback
       {
         String message = in.read_string ();
         this.callback (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CallbackApp/MsgCallback:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _MsgCallbackImplBase
