package Callback.CallbackApp;


/**
* CallbackApp/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CallbackExample.idl
* sobota, 5 listopad 2005 14:50:17 CET
*/

public interface Message extends MessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Message
