package Callback.CallbackApp;

/**
* CallbackApp/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CallbackExample.idl
* sobota, 5 listopad 2005 14:50:17 CET
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public Callback.CallbackApp.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (Callback.CallbackApp.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Callback.CallbackApp.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Callback.CallbackApp.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Callback.CallbackApp.MessageHelper.type ();
  }

}
