package Callback.CallbackApp;

/**
* CallbackApp/MessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CallbackExample.idl
* sobota, 5 listopad 2005 14:50:17 CET
*/

public interface MessageOperations 
{
  String sendMessage (Callback.CallbackApp.MsgCallback objRef, String message);
} // interface MessageOperations
