package Callback.CallbackApp;


/**
* CallbackApp/MsgCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from CallbackExample.idl
* sobota, 5 listopad 2005 14:50:17 CET
*/

public interface MsgCallbackOperations 
{
  void callback (String message);
} // interface MsgCallbackOperations
